### ISSUE TITLE
Is this project still active ?

### ISSUE THREAD

**Issue by aelbarkani** [aws/aws-service-operator-k8s#44]
Hi,

Is there an ETA for this operator ? It would be great if we can have an officially supported operator for AWS services. Looking forward for it !

**Comment by mhausenblas** [comment]
We're working on the MVP, see #22.

**Comment by benlangfeld** [comment]
@mhausenblas Is there a team at Amazon dedicated to this project? I understand that it's early, but nothing has been committed to master since January and discussions appear to have got no further than a proposed list of things to include in the MVP. Is work actually happening internally and just not being exposed, or is the project on hold?

**Comment by mhausenblas** [comment]
@benlangfeld have a look at the [mvp](https://github.com/aws/aws-controllers-k8s/tree/mvp) branch. In fact, good timing, we're very close to merging into the main branch.
